// get todos
export const GET_TODOS_LOADING = 'GET_TODOS_LOADING'
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS'
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE'

// delete todo
export const DELETE_TODO_LOADING = 'DELETE_TODO_LOADING'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'

// create todo
export const CREATE_TODO_LOADING = 'CREATE_TODO_LOADING'
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS'
export const CREATE_TODO_FAILURE = 'CREATE_TODO_FAILURE'
export const CREATE_TODO_MODAL = 'CREATE_TODO_MODAL'

// edit todo
export const EDIT_TODO_LOADING = 'EDIT_TODO_LOADING'
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS'
export const EDIT_TODO_FAILURE = 'EDIT_TODO_FAILURE'
export const EDIT_TODO_MODAL = 'EDIT_TODO_MODAL'
export const STORE_TODO_TITLE = 'STORE_TODO_TITLE'
export const STORE_TODO_ID = 'STORE_TODO_ID'